name = "favicon"
main = "src/index.ts"
compatibility_date = "2024-01-01"
assets = { directory = "./public" }

[[kv_namespaces]]
binding = "FAVICON_META"
id = "2aa8bfd9411e43908a4563fd00255002"

# Route configuration for custom domain
[[routes]]
pattern = "favicon.show/*"
zone_name = "favicon.show"